import csv,os
from datetime import datetime as dt

stock_name = {'GAIL', 'MCDOWELL-N', 'DCBBANK', 'IBULHSGFIN', 'SUZLON', 'UBL', 'UJJIVAN', 'AARTIIND_CLOSED_CLOSED', '', 'HDIL', 'DJIA', 'SINTEX', 'LTTS', 'METROPOLIS', 'JISLJALEQS', 'FINNIFTY', 'FEDERALBNK', 'GSPL', 'TITAN', 'ICIL', 'INFRATEL', 'ADANIENT', 'UCOBANK', 'AMARAJABAT', 'TORNTPHARM', 'NIFTYPSE', 'INFIBEAM', 'OFSS', 'UNIONBANK', 'OBEROIRLTY', 'SUNPHARMA', 'BHARATFIN', 'GODREJIND', 'SOUTHBANK', 'ABB', 'NIFTYINFRA', 'JSWENERGY', 'HEXAWARE', 'CANFINHOME', 'INDHOTEL', 'L&TFH', 'VGUARD', 'COFORGE', 'IPCALAB', 'TATAPOWER', 'PEL_CLOSED', 'VEDL', 'MPHASIS', 'SRTRANSFIN', 'NAVINFLUOR', 'COLPAL', 'BSOFT', 'NIFTYIT', 'NIFTYMID50', 'SRF', 'TATAMOTORS', 'YESBANK', 'PCJEWELLER', 'IBREALEST', 'GODFRYPHLP', 'NHPC', 'SUNTV', 'ORIENTBANK', 'NESTLEIND', 'SBICARD', 'MGL', 'TRENT', 'IOC', 'ACC', 'ADANIPORTS', 'BANKBARODA', 'BANKNIFTY', 'DALMIABHA', 'APLLTD', 'SAIL', 'CAPF', 'LUPIN', 'PTC', 'APOLLOTYRE', 'TCS', 'BALRAMCHIN', 'JETAIRWAYS', 'IFCI', 'IGL', 'INDIANB', 'RAMCOCEM', 'AUROPHARMA', 'HINDCOPPER', 'IDFC', 'JUBLFOOD', 'ASHOKLEY', 'NIFTY', 'ESCORTS', 'SYNGENE', 'WOCKPHARMA', 'LICHSGFIN', 'TATASTEEL', 'CAIRN', 'ASIANPAINT', 'OIL', 'KSCL', 'NAM-INDIA', 'PFIZER', 'CUB', 'HDFC', 'ONGC', 'RPOWER', 'DRREDDY', 'CHENNPETRO', 'POWERGRID', 'WIPRO', 'EQUITAS', 'ASTRAL', 'CESC', 'INFY', 'ICICIBANK', 'MANAPPURAM', 'ALKEM', 'NIITTECH', 'MRPL', 'POLYCAB', 'DELTACORP', 'REPCOHOME', 'MCLEODRUSS', 'TORNTPOWER', 'CIPLA', 'AUBANK', 'BEML', 'HAVELLS', 'PFC', 'IDEA', 'S&P500', 'SHREECEM', 'BANDHANBNK', 'IEX', 'ATUL', 'LAURUSLABS', 'GNFC', 'AARTIIND', 'BAJFINANCE', 'UNITECH', 'DISHTV', 'CGPOWER', 'CHAMBLFERT', 'HINDALCO', 'TECHM', 'CUMMINSIND', 'GMRINFRA', 'SYNDIBANK', 'PAGEIND', 'HDFCBANK', 'ICICIGI', 'BIOCON', 'CONCOR', 'GRASIM', 'INDIGO', 'MUTHOOTFIN', 'BHARTIARTL', 'ITC', 'BAJAJ-AUTO', 'NCC', 'KPIT', 'NATIONALUM', 'CROMPTON', 'DALBHARAT', 'EXIDEIND', 'NAUKRI', 'DABUR', 'MOTHERSUMI', 'MOTHERSON', 'ARVIND', 'BHEL', 'ULTRACEMCO', 'ABIRLANUVO', 'PNB', 'KTKBANK', 'LT', 'MFSL', 'TATAGLOBAL', 'PVR', 'APOLLOHOSP', 'INDUSINDBK', 'KOTAKBANK', 'VOLTAS', 'STAR', 'AXISBANK', 'HINDUNILVR', 'RELCAPITAL', 'AMBUJACEM', 'DIXON', 'IOB', 'INTELLECT', 'M&M', 'AJANTPHARM', 'ENGINERSIN', 'SBIN', 'DEEPAKNTR', 'HINDZINC', 'MIDCPNIFTY', 'RAIN', 'PEL', 'JKCEMENT', 'ABBOTINDIA', 'ANDHRABANK', 'COALINDIA', 'BALKRISIND', 'TATACHEM', 'FORTIS', 'TATACONSUM', 'JSWSTEEL', 'MINDTREE_CLOSED', 'ZYDUSLIFE', 'NBCC', 'ZEEL', 'BHARATFORG', 'BPCL', 'HEROMOTOCO', 'HCLTECH', 'GODREJCP', 'LTIM', 'LALPATHLAB', 'CENTURYTEX', 'CEATLTD', 'PIDILITIND', 'WHIRLPOOL', 'GSFC', 'NMDC_CLOSED', 'BEL', 'SREINFRA', 'GLENMARK', 'JPASSOCIAT', 'HCC', 'SKSMICRO', 'TATACOMM', 'ABFRL', 'KAJARIACER', 'IDFCFIRSTB', 'ADANIPOWER', 'PERSISTENT', 'JINDALSTEL', 'RBLBANK', 'INDIAVIX', 'SBILIFE', 'FSL', 'BANKINDIA', 'BATAINDIA', 'FTSE100', 'RDEL', 'DHFL', 'RAYMOND', 'MRF', 'COROMANDEL', 'IDBI', 'NIFTYCPSE', 'BOSCHLTD', 'M&MFIN', 'NMDC', 'BERGEPAINT', 'GRANULES', 'NTPC', 'GUJGASLTD', 'LTI', 'EICHERMOT', 'IRB', 'PETRONET', 'CHOLAFIN', 'INDUSTOWER', 'HDFCLIFE', 'HAL', 'IDFCBANK', 'GODREJPROP', 'SIEMENS', 'RELIANCE', 'IRCTC', 'CASTROLIND', 'MARICO', 'ICICIPRULI', 'RNAVAL', 'DIVISLAB', 'BAJAJFINSV', 'ALBK', 'HINDPETRO', 'HDFCAMC', 'RECLTD', 'DLF', 'HONAUT', 'ABCAPITAL', 'MARUTI', 'RELINFRA', 'TATAMTRDVR', 'JUSTDIAL', 'TV18BRDCST', 'PIIND', 'CROMPGREAV', 'INDIACEM', 'TATAELXSI', 'CANBK', 'INDIAMART', 'TVSMOTOR', 'RCOM', 'SHRIRAMFIN', 'MCX', 'BRITANNIA', 'UPL'}


stock_name = list(stock_name)

for i in range(1,len(stock_name)):
    with open('data-1674364923034.csv') as csv_file:
        csv_reader = csv.reader(csv_file, delimiter=',')
        line_count = 0
        cost=0
        f_name = "stocks\\" + str(stock_name[i]) + ".csv"
        print(f_name)
        with open(f_name, 'w', newline='') as file:
            writer = csv.writer(file)
            for row in csv_reader:
                if line_count == 0: 
                    writer.writerow(["Symbol" ,"Date", "wap","lot_size","Expiry_date"])
                    print()
                    line_count += 1
                elif row[1]==stock_name[i]  :
                    writer.writerow([row[1],row[-2],row[-3],row[-6],row[2]])
                    line_count += 1
print(f'Processed {line_count} lines.')
